class NotFoundError(Exception):

    pass


class AlreadyCreatedError(Exception):

    pass
